# Generated by Django 5.2 on 2025-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('stock', models.BigIntegerField(default=0)),
                ('balance', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_items',
            },
        ),
    ]
