# Generated by Django 5.2 on 2025-04-11 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tbl_sells',
            },
        ),
        migrations.CreateModel(
            name='SellsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('header_code', models.ForeignKey(db_column='header_code', on_delete=django.db.models.deletion.CASCADE, to='purchases.purchases')),
                ('item_code', models.ForeignKey(db_column='item_code', on_delete=django.db.models.deletion.CASCADE, to='items.items')),
            ],
            options={
                'db_table': 'tbl_sells_dtl',
            },
        ),
    ]
