# Generated by Django 5.2 on 2025-04-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellsdetails',
            name='header_code',
            field=models.ForeignKey(db_column='header_code', on_delete=django.db.models.deletion.CASCADE, to='sells.sells'),
        ),
    ]
