### ITEMS ###

#get list all item
GET http://127.0.0.1:8000/items/
Content-Type: application/json

###
#save items
POST http://127.0.0.1:8000/items/
Content-Type: application/json

{
    "code": "I-001",
    "name": "History Book",
    "unit": "Psc",
    "description": "Books that tells history of the ancient"
}

###
#get detail items
GET http://127.0.0.1:8000/items/T-004
Content-Type: application/json

###
#update items
PUT http://127.0.0.1:8000/items/T-005
Content-Type: application/json

{
    "code": "T-001",
    "name": "Item-1 update",
    "unit": "Psc",
    "description": "Product items 1 - update"
}

###
#soft delete items
DELETE http://127.0.0.1:8000/items/T-007
Content-Type: application/json

###

### PURCHASES ###

#get list purchases
GET http://127.0.0.1:8000/purchases/
Content-Type: application/json

###
#save data puchase
POST http://127.0.0.1:8000/purchases/
Content-Type: application/json

{
    "code": "P-002",
    "description": "Restock history books"
}

###
#get purchases data
GET http://127.0.0.1:8000/purchases/P-002
Content-Type: application/json

###
#update data puchase
PUT http://127.0.0.1:8000/purchases/P-001
Content-Type: application/json

{
    "code": "P-001",
    "description": "Buy history books"
}

###
#update data puchase
DELETE http://127.0.0.1:8000/purchases/P-002
Content-Type: application/json

###


# PURCHASES DETAILS
#get list purchases details
GET http://127.0.0.1:8000/purchases/P-001/details
Content-Type: application/json

###
#save list purchases
POST http://127.0.0.1:8000/purchases/P-002/details
Content-Type: application/json

{
    "item_code": "I-001",
    "quantity": 10,
    "unit_price": 50000,
    "header_code": "P-002"
}

###

### SELLS ###

#get list all sells
GET http://127.0.0.1:8000/sell/
Content-Type: application/json

###
#save data sells
POST http://127.0.0.1:8000/sell/
Content-Type: application/json

{
    "code": "S-001",
    "description": "Sell history books to library"
}

###
#get data sells
GET http://127.0.0.1:8000/sell/S-002
Content-Type: application/json

###
#update data puchase
PUT http://127.0.0.1:8000/sell/S-002
Content-Type: application/json

{
    "code": "S-002",
    "description": "Purchase S-002 - updated"
}

###
#update data puchase
DELETE http://127.0.0.1:8000/sell/S-004
Content-Type: application/json

###
#get sells detail
GET http://127.0.0.1:8000/sell/S-001/details
Content-Type: application/json

###
#save sells detail
POST http://127.0.0.1:8000/sell/S-001/details
Content-Type: application/json

{
    "item_code": "I-001",
    "quantity": 15,
    "header_code": "S-001"
}